AGOL_USERNAME = "mkuchavaram@islander.tamucc.edu"
AGOL_PASSWORD = "Mallesh@1965"
FEATURE_LAYER_URL = "https://services1.arcgis.com/BSnEnFfEn54YLVeq/arcgis/rest/services/mosquito_reports_RT_1/FeatureServer/0"

